//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoutesOfContacts.View.Contents.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class appResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal appResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RoutesOfContacts.View.Contents.Resources.appResource", typeof(appResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved..
        /// </summary>
        internal static string allRightsReserved {
            get {
                return ResourceManager.GetString("allRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate.
        /// </summary>
        internal static string alternate {
            get {
                return ResourceManager.GetString("alternate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, check the origin&apos;s and destination&apos;s informations..
        /// </summary>
        internal static string checkInformations {
            get {
                return ResourceManager.GetString("checkInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments and Suggestions to:.
        /// </summary>
        internal static string commentsAndSuggestionsTo {
            get {
                return ResourceManager.GetString("commentsAndSuggestionsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string contacts {
            get {
                return ResourceManager.GetString("contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contribute/donate.
        /// </summary>
        internal static string contributeDonate {
            get {
                return ResourceManager.GetString("contributeDonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination contact.
        /// </summary>
        internal static string destinationContact {
            get {
                return ResourceManager.GetString("destinationContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by:.
        /// </summary>
        internal static string developedBy {
            get {
                return ResourceManager.GetString("developedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, fill in the information of the origin and destination..
        /// </summary>
        internal static string fillContacts {
            get {
                return ResourceManager.GetString("fillContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        internal static string languages {
            get {
                return ResourceManager.GetString("languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has ocurred in the location service..
        /// </summary>
        internal static string locationError {
            get {
                return ResourceManager.GetString("locationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location not found..
        /// </summary>
        internal static string locationNotFound {
            get {
                return ResourceManager.GetString("locationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location service is working, but it cannot get location data..
        /// </summary>
        internal static string locationServiceNoData {
            get {
                return ResourceManager.GetString("locationServiceNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location service is not enabled on the device..
        /// </summary>
        internal static string locationServiceNotEnabled {
            get {
                return ResourceManager.GetString("locationServiceNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My position.
        /// </summary>
        internal static string myPosition {
            get {
                return ResourceManager.GetString("myPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origin contact.
        /// </summary>
        internal static string originContact {
            get {
                return ResourceManager.GetString("originContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate and review.
        /// </summary>
        internal static string rateAndReview {
            get {
                return ResourceManager.GetString("rateAndReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routes of Contacts.
        /// </summary>
        internal static string routesOfContacts {
            get {
                return ResourceManager.GetString("routesOfContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The origin and destination can not be the same..
        /// </summary>
        internal static string sameOriginAndDestination {
            get {
                return ResourceManager.GetString("sameOriginAndDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a contact....
        /// </summary>
        internal static string selectContact {
            get {
                return ResourceManager.GetString("selectContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the language:.
        /// </summary>
        internal static string selectLanguage {
            get {
                return ResourceManager.GetString("selectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show route.
        /// </summary>
        internal static string showRoute {
            get {
                return ResourceManager.GetString("showRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talk to the developer.
        /// </summary>
        internal static string talkToTheDeveloper {
            get {
                return ResourceManager.GetString("talkToTheDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
    }
}
